<?php
/** Customizer template - renders the customizer interface */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}
?>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

<script type="module">
/**
 * Converts an HTML element (specifically designed for SVG elements) into a Data URL image string.
 *
 * @param {SVGElement} element The SVG element to convert.
 * @returns {Promise<string>} A promise that resolves with the Data URL string.
 */
window.htmlElementToImage = function(element) {
    return new Promise((resolve, reject) => {
        // 1. Check if the element is an SVG element
        if (!element || element.tagName.toLowerCase() !== 'svg') {
            return reject(new Error('Element is not a valid SVG element.'));
        }

        // 2. Serialize the SVG element to an XML string
        const svgString = new XMLSerializer().serializeToString(element);

        // 3. Encode the string for use in a Data URL
        // Using encodeURIComponent is often more robust than btoa/base64 for SVG,
        // especially to handle special characters.
        const encodedSvg = encodeURIComponent(svgString);

        // 4. Construct the Data URL
        // The format is: data:image/svg+xml;charset=utf-8, <encoded_svg_string>
        const dataUrl = `data:image/svg+xml;charset=utf-8,${encodedSvg}`;

        // The image is already in data URL format, resolve immediately.
        // If you needed to convert it to a PNG/JPEG (which is more complex and requires a Canvas),
        // you'd do that here, but for SVG->Data URL, this is the most direct method.
        resolve(dataUrl);
    });
};
</script>

<div class="fsc-container">
    <div class="fsc-customizer-wrapper">
        
        <!-- Preview Section -->
        <div class="fsc-preview-section">
            <div class="fsc-preview-title">Live Preview</div>
            <div class="fsc-preview-area">
                <div class="fsc-preview-content">
                    <!-- Logo SVG -->
                    <div class="fsc-logo-container">
                        <?php echo $product_logo_content; ?>
                    </div>
                    
                    <!-- Text SVG - will be populated by JavaScript -->
                    <div class="fsc-text-container">
                        <!-- Text SVG will be generated by customizer.js -->
                    </div>
                </div>
            </div>
            <div class="fsc-thumbnails">
                <!-- Thumbnail previews can be added here -->
            </div>
        </div>
        
        <!-- Customization Panel -->
        <div class="fsc-customization-panel">
            <!-- Product Info -->
            <div class="fsc-product-info" data-product-id="<?php echo $product_data ? $product_data->ID : 0; ?>">
                <div class="fsc-product-name" data-product-name="<?php echo esc_attr($product_data ? $product_data->post_title : 'Custom Product'); ?>">
                    <?php echo $product_data ? $product_data->post_title : 'Custom Product'; ?>
                </div>
                <div class="fsc-product-price" 
                     data-product-price="<?php echo esc_attr($product_price); ?>" 
                     data-product-sale-price="<?php echo esc_attr($product_sale_price); ?>">
                    <?php 
                    $display_price = !empty($product_sale_price) ? $product_sale_price : $product_price;
                    echo '$' . ($display_price ?: '29.99'); 
                    ?> - <?php echo $product_material; ?>
                </div>
            </div>
            
            <!-- Color Selection -->
            <div class="fsc-form-group">
                <h4>Print Color</h4>
                <div class="fsc-selected-color" style="margin-bottom:8px;font-size:13px;color:#444;">
                    Selected: <span id="fsc-selected-color-name">None</span>
                </div>
                <div class="fsc-color-grid">
                    <?php foreach ($colors as $color_name => $color_value): ?>
                        <div class="fsc-color-item" style="display:inline-flex;flex-direction:column;align-items:center;gap:4px;margin:4px;">
                            <div class="fsc-color-option" 
                                 data-color="<?php echo esc_attr($color_name); ?>" 
                                 style="background-color: <?php echo esc_attr($color_value); ?>; width: 28px; height: 28px; border-radius: 4px; box-shadow: inset 0 0 0 1px rgba(0,0,0,0.1); cursor: pointer;"
                                 title="<?php echo esc_attr($color_name); ?>">
                            </div>
                            <div class="fsc-color-label" style="font-size: 12px; color: #555; max-width: 64px; text-align: center; word-break: break-word; line-height: 1.1;">
                                <?php echo esc_html($color_name); ?>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        
            
            <!-- Text Fields -->
            <div class="fsc-form-group">
                <h4>Custom Text</h4>
                
                <!-- Dynamic Template Fields Container -->
                <div id="fsc-template-fields">
                    <!-- Template text fields will be populated here by JavaScript -->
                </div>
            </div>
            
            <!-- Features/Benefits -->
            <div class="fsc-form-group fsc-features">
                <h4>Benefits</h4>
                <ul class="fsc-feature-list">
                    <?php foreach ($product_features as $feature): ?>
                        <li><?php echo esc_html($feature); ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
            
            <!-- Actions -->
            <div class="fsc-actions">
                <div class="fsc-quantity-group">
                    <button class="fsc-quantity-btn" id="fsc-quantity-minus">-</button>
                    <input type="number" id="fsc-quantity" value="1" min="1" max="100" class="fsc-quantity-input">
                    <button class="fsc-quantity-btn" id="fsc-quantity-plus">+</button>
                </div>
                <div class="fsc-button-group">
                    <button class="fsc-btn fsc-btn-primary fsc-btn-add-cart">ADD TO CART</button>
                    <button class="fsc-btn fsc-btn-secondary fsc-btn-reset">🔄 RESET</button>
                </div>
            </div>
            
            <!-- Checkout Section -->
            <div class="fsc-checkout-section">
                <button class="fsc-btn fsc-btn-checkout">CHECK OUT</button>
            </div>
        </div>
        
    </div>
</div>

<!-- Hidden form for AJAX submissions -->
<form id="fsc-customization-form" style="display: none;">
    <input type="hidden" name="action" value="save_customization">
    <input type="hidden" name="nonce" value="<?php echo wp_create_nonce('fsc_nonce'); ?>">
    <input type="hidden" name="product_id" id="fsc-form-product-id" value="<?php echo $product_data ? $product_data->ID : 0; ?>">
    <input type="hidden" name="vin" id="fsc-form-vin">
    <input type="hidden" name="truck_no" id="fsc-form-truck">
    <input type="hidden" name="print_color" id="fsc-form-color">
    <input type="hidden" name="vinyl_material" id="fsc-form-material">
    <input type="hidden" name="quantity" id="fsc-form-quantity">
</form>

<script>
// AJAX object for customizer
var ajaxObj = {
    ajax_url: '<?php echo admin_url('admin-ajax.php'); ?>',
    nonce: '<?php echo wp_create_nonce('apd_ajax_nonce'); ?>',
    fsc_nonce: '<?php echo wp_create_nonce('fsc_nonce'); ?>',
    cart_url: '<?php echo home_url(get_option('apd_cart_url', '/cart/')); ?>',
    checkout_url: '<?php echo home_url(get_option('apd_checkout_url', '/checkout/')); ?>',
    products_url: '<?php echo home_url(get_option('apd_products_url', '/products/')); ?>',
    orders_url: '<?php echo home_url(get_option('apd_orders_url', '/my-orders/')); ?>',
    customizer_url: '<?php echo home_url(get_option('apd_customizer_url', '/customizer/')); ?>',
    thank_you_url: '<?php echo home_url(get_option('apd_thank_you_url', '/thank-you/')); ?>',
    product_id: '<?php echo $product_data ? $product_data->ID : 0; ?>'
};

// Ensure compatibility with scripts expecting `apd_ajax`
// Map the local config to the global name used across JS files
window.apd_ajax = window.apd_ajax || ajaxObj;
var apd_ajax = window.apd_ajax;

// Set default values for FSC
window.fscDefaults = {
    product_id: '<?php echo $product_data ? $product_data->ID : 0; ?>',
    product_name: '<?php echo $product_data ? esc_js($product_data->post_title) : 'Custom Freight Sign'; ?>',
    product_price: '<?php echo $product_price ?: '29.99'; ?>',
    base_price: '<?php echo $product_price ?: '29.99'; ?>', // Base price (same as product_price)
    product_sale_price: '<?php echo $product_sale_price ?: ''; ?>'
};
</script>

<script>
// Simple Buy Now handler for customizer
(function(){
    async function buyNowHandler(e){
        e.preventDefault();
        const btn = e.currentTarget;
        btn.disabled = true;
        const quantity = parseInt(document.getElementById('fsc-quantity').value || '1',10);
        
        // Get price information from FSC object if available, otherwise use defaults
        let basePrice = 0;
        let salePrice = null;
        let materialPrice = 0;
        let productPrice = window.fscDefaults.product_price || 0;
        
        if (window.FSC) {
            // Try to get base price from FSC
            basePrice = FSC.baseProductPrice || parseFloat(window.fscDefaults.base_price) || 0;
            salePrice = FSC.salePrice || (window.fscDefaults.product_sale_price ? parseFloat(window.fscDefaults.product_sale_price) : null);
            
            // Get material price
            const currentMaterial = FSC.currentMaterial || document.getElementById('fsc-form-material')?.value || '';
            if (currentMaterial) {
                // Try to get material price from selected material element
                const materialEl = document.querySelector('.fsc-material-outline-option[data-material="' + currentMaterial + '"]');
                if (materialEl) {
                    materialPrice = parseFloat(materialEl.getAttribute('data-material-price')) || 0;
                } else if (FSC.materialsMap && FSC.materialsMap[currentMaterial]) {
                    const materialData = FSC.materialsMap[currentMaterial];
                    if (typeof materialData === 'object' && materialData.price !== undefined) {
                        materialPrice = parseFloat(materialData.price) || 0;
                    }
                }
            }
            
            // Calculate product price: base_price (or sale_price) + material_price
            const basePriceToUse = salePrice || basePrice || parseFloat(window.fscDefaults.product_price) || 0;
            productPrice = basePriceToUse + materialPrice;
        } else {
            // Fallback: use defaults
            basePrice = parseFloat(window.fscDefaults.base_price) || parseFloat(window.fscDefaults.product_price) || 0;
            salePrice = window.fscDefaults.product_sale_price ? parseFloat(window.fscDefaults.product_sale_price) : null;
            productPrice = salePrice || basePrice;
        }
        
        const payload = {
            product_id: window.fscDefaults.product_id || ajaxObj.product_id,
            product_name: window.fscDefaults.product_name || '',
            product_price: productPrice, // Total price (base + material)
            base_price: basePrice,
            sale_price: salePrice,
            material_price: materialPrice,
            quantity: quantity,
            print_color: document.getElementById('fsc-form-color')?.value || FSC?.currentColor || '',
            vinyl_material: document.getElementById('fsc-form-material')?.value || FSC?.currentMaterial || '',
            text_fields: (window.FSC && typeof FSC.getTextFields === 'function') ? FSC.getTextFields() : {},
            template_data: (window.FSC && typeof FSC.getTemplateData === 'function') ? FSC.getTemplateData() : {},
            preview_image_svg: null
        };

        // Try to capture preview image if available (but limit size to avoid localStorage issues)
        try{
            const previewArea = document.querySelector('.fsc-preview-content');
            if (previewArea && window.htmlElementToImage) {
                const previewImage = await window.htmlElementToImage(previewArea, 2);
                // Only include preview if it's not too large (max 100KB to avoid localStorage issues)
                if (previewImage && previewImage.length < 100000) {
                    payload.preview_image_svg = previewImage;
                    console.log('✅ Buy Now: Preview image captured, size:', previewImage.length, 'bytes');
                } else if (previewImage) {
                    console.warn('⚠️ Buy Now: Preview image too large (' + previewImage.length + ' bytes), skipping to avoid localStorage issues');
                    // Don't include preview_image_svg if too large
                }
            } else {
                console.log('ℹ️ Buy Now: Preview area or htmlElementToImage not available, skipping preview capture');
            }
        }catch(err){ 
            console.warn('⚠️ Buy Now: failed to capture preview:', err);
            // Continue without preview image - it's not critical
        }

        // Persist checkout payload locally and redirect to checkout page
        try {
            // Validate payload has required fields
            if (!payload.product_id || !payload.product_name) {
                console.error('Buy Now: Invalid payload - missing product_id or product_name', payload);
                alert('Error: Missing product information. Please refresh the page and try again.');
                btn.disabled = false;
                return;
            }
            
            // Ensure price is valid
            if (!payload.product_price || payload.product_price <= 0) {
                console.warn('Buy Now: Invalid price, using default', payload);
                payload.product_price = parseFloat(window.fscDefaults.product_price) || 29.99;
                payload.base_price = parseFloat(window.fscDefaults.base_price) || payload.product_price;
            }
            
            // Log payload before saving
            console.log('🛒 Buy Now: Saving payload to localStorage:', payload);
            console.log('🛒 Buy Now: Payload keys:', Object.keys(payload));
            console.log('🛒 Buy Now: Product ID:', payload.product_id);
            console.log('🛒 Buy Now: Product Name:', payload.product_name);
            console.log('🛒 Buy Now: Price:', payload.product_price);
            
            // Check payload size before saving (localStorage has ~5-10MB limit, but we'll be conservative)
            const payloadString = JSON.stringify(payload);
            const payloadSize = new Blob([payloadString]).size;
            console.log('📦 Buy Now: Payload size:', payloadSize, 'bytes');
            
            // If payload is too large (>500KB), remove preview image and try again
            if (payloadSize > 500000) {
                console.warn('⚠️ Buy Now: Payload too large, removing preview image');
                delete payload.preview_image_svg;
                delete payload.preview_image_png;
                const reducedPayloadString = JSON.stringify(payload);
                const reducedSize = new Blob([reducedPayloadString]).size;
                console.log('📦 Buy Now: Reduced payload size:', reducedSize, 'bytes');
                
                if (reducedSize > 500000) {
                    console.error('❌ Buy Now: Payload still too large even without preview image!');
                    alert('Error: Checkout data is too large. Please try again or contact support.');
                    btn.disabled = false;
                    return;
                }
                
                // Use reduced payload
                localStorage.setItem('apd_checkout_payload_oneclick', reducedPayloadString);
                const saved = localStorage.getItem('apd_checkout_payload_oneclick');
                if (!saved || saved !== reducedPayloadString) {
                    console.error('Buy Now: Failed to save reduced payload to localStorage!');
                    alert('Error: Failed to save checkout data. Please try again.');
                    btn.disabled = false;
                    return;
                }
            } else {
                // Save one-click payload under dedicated key
                localStorage.setItem('apd_checkout_payload_oneclick', payloadString);
                
                // Verify it was saved
                const saved = localStorage.getItem('apd_checkout_payload_oneclick');
                if (!saved || saved !== payloadString) {
                    console.error('Buy Now: Failed to save payload to localStorage!');
                    alert('Error: Failed to save checkout data. Please try again.');
                    btn.disabled = false;
                    return;
                }
            }
            
            console.log('✅ Buy Now: Payload saved successfully to apd_checkout_payload_oneclick');
            
            // Clear cart (optional) to avoid confusion
            try { localStorage.removeItem('apd_cart'); } catch(_) {}
            // Clear cart selection to avoid filtering issues
            try { localStorage.removeItem('apd_cart_selected'); } catch(_) {}
            
            // Redirect to checkout with instant flag so checkout reads the oneclick payload
            var target = (ajaxObj && ajaxObj.checkout_url) ? ajaxObj.checkout_url : '/checkout/';
            if (target.indexOf('?') === -1) {
                target += '?instant=true';
            } else {
                target += '&instant=true';
            }
            
            console.log('🛒 Buy Now: Redirecting to checkout:', target);
            window.location.href = target;
            return;
        } catch (err) {
            console.error('❌ Buy Now local persist error:', err);
            console.error('❌ Error stack:', err.stack);
            console.error('❌ Payload that caused error:', payload);
            alert('Failed to start checkout. Please try again or contact support.');
            btn.disabled = false;
        }
    }

    document.addEventListener('DOMContentLoaded', function(){
        const buyBtns = document.querySelectorAll('.fsc-btn-buy-now');
        buyBtns.forEach(b => b.addEventListener('click', buyNowHandler));
    });
})();
</script>
